version: 2
jobs:
  build:
    docker:
      - image: 'circleci/ubuntu:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install --immutable
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn semantic-release || true
