# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: yarn install
      - run: yarn build
      - run: cd example
      - run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './example/build'
          production-branch: master
          github-token: ${{ env.GITHUB_TOKEN }}
          deploy-message: 'Deploy in Netlify from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
        timeout-minutes: 1
