name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: yarn install
      - run: yarn build
      - name: Test
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
      - name: Build StoryBook
        run:  yarn build-storybook
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'storybook-static'
          production-branch: master
          deploy-message: 'Deploy in Netlify from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
        - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo  ${{ secrets.GITHUB_TOKEN }} && npx semantic-release
