name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12']
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: End to end test
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
